# Generated by Django 4.1a1 on 2022-06-09 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apiapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AccessToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("accesstoken", models.CharField(max_length=30)),
            ],
        ),
    ]
