# Generated by Django 4.0.4 on 2022-06-07 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(max_length=500)),
                ('author', models.TextField(max_length=20)),
                ('date', models.DateField()),
                ('label', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Url',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url1', models.URLField(blank=True, null=True)),
                ('url2', models.URLField(blank=True, null=True)),
                ('url3', models.URLField(blank=True, null=True)),
                ('url4', models.URLField(blank=True, null=True)),
                ('url5', models.URLField(blank=True, null=True)),
                ('url6', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Visual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pie', models.ImageField(upload_to='piechart/')),
                ('wordcloud', models.ImageField(upload_to='wordcloud/')),
                ('plot', models.ImageField(upload_to='plotchart/')),
                ('emotion', models.CharField(max_length=10)),
            ],
        ),
    ]
